### ISSUE TITLE
Voice Not passing

### ISSUE THREAD

**Issue by n8acl** [jess-sys/dmr-bridge-discord#3]
Hi Me again.... Your favorite pest.

Ok so I got the bot to be able to read the commands, however, when I do, after a few seconds I get back in the text channel that I issued the command in

```Error joining the channel```

and it does not pass audio. I know it is receiving audio from the other side as I can see the packet information scrolling up the console, but it does not pass audio to or from Discord. I did try resetting all the correct permissions in the Developer Portal

No other errors in the console, so not sure what else I can send.

This is a recent thing and I think it goes back to the changes that Discord made recently, but again, I am not sure.

Thanks again! You guys are the best!

**Comment by jess-sys** [comment]
Hi @n8acl, thank you for your detailed inputs on this project, it is really appreciated!

We are using the [serenity-rs library](https://github.com/serenity-rs/serenity) to handle the Discord API calls, and [Songbird](https://github.com/serenity-rs/serenity) to handle the Discord voice API. 

I was able to find an issue matching your bug report, see https://github.com/serenity-rs/serenity/issues/2379.

Luckily, it seems like a fix has been implemented in [Songbird version 0.3.2](https://github.com/serenity-rs/songbird/releases/tag/v0.3.2), see https://github.com/serenity-rs/songbird/pull/170.

We are actively working on an update using version 0.3.2 of Songbird! Expect it to be available later today.

Thanks again for your support! ;)

**Comment by jess-sys** [comment]
Hi again,

[Version 0.2.0](https://github.com/jess-sys/dmr-bridge-discord/releases/tag/v0.2.0) is out!

Let me know if you experience any other issue.
